// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: grpc/api/gps.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Пустой запрос
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_api_gps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{0}
}

// Health check
type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "OK"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{1}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PointsNearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Radius        float64                `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsNearbyRequest) Reset() {
	*x = PointsNearbyRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsNearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsNearbyRequest) ProtoMessage() {}

func (x *PointsNearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsNearbyRequest.ProtoReflect.Descriptor instead.
func (*PointsNearbyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{2}
}

func (x *PointsNearbyRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *PointsNearbyRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *PointsNearbyRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type PointsNearbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*NearbyPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsNearbyResponse) Reset() {
	*x = PointsNearbyResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsNearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsNearbyResponse) ProtoMessage() {}

func (x *PointsNearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsNearbyResponse.ProtoReflect.Descriptor instead.
func (*PointsNearbyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{3}
}

func (x *PointsNearbyResponse) GetPoints() []*NearbyPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type NearbyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PointId       string                 `protobuf:"bytes,1,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyPoint) Reset() {
	*x = NearbyPoint{}
	mi := &file_grpc_api_gps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyPoint) ProtoMessage() {}

func (x *NearbyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyPoint.ProtoReflect.Descriptor instead.
func (*NearbyPoint) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{4}
}

func (x *NearbyPoint) GetPointId() string {
	if x != nil {
		return x.PointId
	}
	return ""
}

func (x *NearbyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NearbyPoint) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *NearbyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyPoint) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsResponse) Reset() {
	*x = GetPointsResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsResponse) ProtoMessage() {}

func (x *GetPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsResponse.ProtoReflect.Descriptor instead.
func (*GetPointsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{5}
}

func (x *GetPointsResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PointId       string                 `protobuf:"bytes,1,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TypeId        string                 `protobuf:"bytes,6,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_grpc_api_gps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{6}
}

func (x *Point) GetPointId() string {
	if x != nil {
		return x.PointId
	}
	return ""
}

func (x *Point) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Point) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Point) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Point) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetKiosksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kiosks        []*Kiosk               `protobuf:"bytes,1,rep,name=kiosks,proto3" json:"kiosks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKiosksResponse) Reset() {
	*x = GetKiosksResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKiosksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKiosksResponse) ProtoMessage() {}

func (x *GetKiosksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKiosksResponse.ProtoReflect.Descriptor instead.
func (*GetKiosksResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{7}
}

func (x *GetKiosksResponse) GetKiosks() []*Kiosk {
	if x != nil {
		return x.Kiosks
	}
	return nil
}

type GetKioskByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKioskByIdRequest) Reset() {
	*x = GetKioskByIdRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKioskByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKioskByIdRequest) ProtoMessage() {}

func (x *GetKioskByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKioskByIdRequest.ProtoReflect.Descriptor instead.
func (*GetKioskByIdRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{8}
}

func (x *GetKioskByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetKioskByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kiosk         *Kiosk                 `protobuf:"bytes,1,opt,name=kiosk,proto3" json:"kiosk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKioskByIdResponse) Reset() {
	*x = GetKioskByIdResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKioskByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKioskByIdResponse) ProtoMessage() {}

func (x *GetKioskByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKioskByIdResponse.ProtoReflect.Descriptor instead.
func (*GetKioskByIdResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{9}
}

func (x *GetKioskByIdResponse) GetKiosk() *Kiosk {
	if x != nil {
		return x.Kiosk
	}
	return nil
}

type Kiosk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kiosk) Reset() {
	*x = Kiosk{}
	mi := &file_grpc_api_gps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kiosk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kiosk) ProtoMessage() {}

func (x *Kiosk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kiosk.ProtoReflect.Descriptor instead.
func (*Kiosk) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{10}
}

func (x *Kiosk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Kiosk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kiosk) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Kiosk) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Kiosk) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Kiosk) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "kiosk" или "poi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_grpc_api_gps_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TerminalPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalPingRequest) Reset() {
	*x = TerminalPingRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalPingRequest) ProtoMessage() {}

func (x *TerminalPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalPingRequest.ProtoReflect.Descriptor instead.
func (*TerminalPingRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{14}
}

func (x *TerminalPingRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalPingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type TerminalPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TerminalId    string                 `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalPingResponse) Reset() {
	*x = TerminalPingResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalPingResponse) ProtoMessage() {}

func (x *TerminalPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalPingResponse.ProtoReflect.Descriptor instead.
func (*TerminalPingResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{15}
}

func (x *TerminalPingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TerminalPingResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalPingResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{16}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{17}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{20}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{21}
}

func (x *RefreshResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreatePointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TypeId        string                 `protobuf:"bytes,5,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePointRequest) Reset() {
	*x = CreatePointRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePointRequest) ProtoMessage() {}

func (x *CreatePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePointRequest.ProtoReflect.Descriptor instead.
func (*CreatePointRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{22}
}

func (x *CreatePointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePointRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreatePointRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

type CreatePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePointResponse) Reset() {
	*x = CreatePointResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePointResponse) ProtoMessage() {}

func (x *CreatePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePointResponse.ProtoReflect.Descriptor instead.
func (*CreatePointResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{23}
}

func (x *CreatePointResponse) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

type UpdatePointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TypeId        string                 `protobuf:"bytes,6,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePointRequest) Reset() {
	*x = UpdatePointRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointRequest) ProtoMessage() {}

func (x *UpdatePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointRequest.ProtoReflect.Descriptor instead.
func (*UpdatePointRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePointRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdatePointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdatePointRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

type UpdatePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePointResponse) Reset() {
	*x = UpdatePointResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointResponse) ProtoMessage() {}

func (x *UpdatePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointResponse.ProtoReflect.Descriptor instead.
func (*UpdatePointResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{25}
}

func (x *UpdatePointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePointRequest) Reset() {
	*x = DeletePointRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointRequest) ProtoMessage() {}

func (x *DeletePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointRequest.ProtoReflect.Descriptor instead.
func (*DeletePointRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{26}
}

func (x *DeletePointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePointResponse) Reset() {
	*x = DeletePointResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointResponse) ProtoMessage() {}

func (x *DeletePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointResponse.ProtoReflect.Descriptor instead.
func (*DeletePointResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{27}
}

func (x *DeletePointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateKioskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKioskRequest) Reset() {
	*x = CreateKioskRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKioskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKioskRequest) ProtoMessage() {}

func (x *CreateKioskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKioskRequest.ProtoReflect.Descriptor instead.
func (*CreateKioskRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{28}
}

func (x *CreateKioskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKioskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKioskRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateKioskRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateKioskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kiosk         *Kiosk                 `protobuf:"bytes,1,opt,name=kiosk,proto3" json:"kiosk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKioskResponse) Reset() {
	*x = CreateKioskResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKioskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKioskResponse) ProtoMessage() {}

func (x *CreateKioskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKioskResponse.ProtoReflect.Descriptor instead.
func (*CreateKioskResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{29}
}

func (x *CreateKioskResponse) GetKiosk() *Kiosk {
	if x != nil {
		return x.Kiosk
	}
	return nil
}

type UpdateKioskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKioskRequest) Reset() {
	*x = UpdateKioskRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKioskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKioskRequest) ProtoMessage() {}

func (x *UpdateKioskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKioskRequest.ProtoReflect.Descriptor instead.
func (*UpdateKioskRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateKioskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateKioskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKioskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateKioskRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateKioskRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type UpdateKioskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKioskResponse) Reset() {
	*x = UpdateKioskResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKioskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKioskResponse) ProtoMessage() {}

func (x *UpdateKioskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKioskResponse.ProtoReflect.Descriptor instead.
func (*UpdateKioskResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateKioskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteKioskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKioskRequest) Reset() {
	*x = DeleteKioskRequest{}
	mi := &file_grpc_api_gps_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKioskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKioskRequest) ProtoMessage() {}

func (x *DeleteKioskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKioskRequest.ProtoReflect.Descriptor instead.
func (*DeleteKioskRequest) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteKioskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteKioskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKioskResponse) Reset() {
	*x = DeleteKioskResponse{}
	mi := &file_grpc_api_gps_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKioskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKioskResponse) ProtoMessage() {}

func (x *DeleteKioskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_gps_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKioskResponse.ProtoReflect.Descriptor instead.
func (*DeleteKioskResponse) Descriptor() ([]byte, []int) {
	return file_grpc_api_gps_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteKioskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_api_gps_proto protoreflect.FileDescriptor

const file_grpc_api_gps_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/api/gps.proto\x12\x03gps\"\a\n" +
	"\x05Empty\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"Q\n" +
	"\x13PointsNearbyRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x01R\x06radius\"@\n" +
	"\x14PointsNearbyResponse\x12(\n" +
	"\x06points\x18\x01 \x03(\v2\x10.gps.NearbyPointR\x06points\"\xc9\x01\n" +
	"\vNearbyPoint\x12\x19\n" +
	"\bpoint_id\x18\x01 \x01(\tR\apointId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategoryB\x0e\n" +
	"\f_description\"7\n" +
	"\x11GetPointsResponse\x12\"\n" +
	"\x06points\x18\x01 \x03(\v2\n" +
	".gps.PointR\x06points\"\xfe\x01\n" +
	"\x05Point\x12\x19\n" +
	"\bpoint_id\x18\x01 \x01(\tR\apointId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x17\n" +
	"\atype_id\x18\x06 \x01(\tR\x06typeId\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAtB\x0e\n" +
	"\f_description\"7\n" +
	"\x11GetKiosksResponse\x12\"\n" +
	"\x06kiosks\x18\x01 \x03(\v2\n" +
	".gps.KioskR\x06kiosks\"%\n" +
	"\x13GetKioskByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x14GetKioskByIdResponse\x12 \n" +
	"\x05kiosk\x18\x01 \x01(\v2\n" +
	".gps.KioskR\x05kiosk\"\xa6\x01\n" +
	"\x05Kiosk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x1d\n" +
	"\rSearchRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"=\n" +
	"\x0eSearchResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.gps.SearchResultR\aresults\"F\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"R\n" +
	"\x13TerminalPingRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"k\n" +
	"\x14TerminalPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vterminal_id\x18\x02 \x01(\tR\n" +
	"terminalId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"'\n" +
	"\x0fRefreshResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xb2\x01\n" +
	"\x12CreatePointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x17\n" +
	"\atype_id\x18\x05 \x01(\tR\x06typeIdB\x0e\n" +
	"\f_description\"7\n" +
	"\x13CreatePointResponse\x12 \n" +
	"\x05point\x18\x01 \x01(\v2\n" +
	".gps.PointR\x05point\"\xc2\x01\n" +
	"\x12UpdatePointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x17\n" +
	"\atype_id\x18\x06 \x01(\tR\x06typeIdB\x0e\n" +
	"\f_description\"/\n" +
	"\x13UpdatePointResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x12DeletePointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeletePointResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x84\x01\n" +
	"\x12CreateKioskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"7\n" +
	"\x13CreateKioskResponse\x12 \n" +
	"\x05kiosk\x18\x01 \x01(\v2\n" +
	".gps.KioskR\x05kiosk\"\x94\x01\n" +
	"\x12UpdateKioskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"/\n" +
	"\x13UpdateKioskResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x12DeleteKioskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteKioskResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcb\a\n" +
	"\n" +
	"GPSService\x12+\n" +
	"\aHealthz\x12\n" +
	".gps.Empty\x1a\x14.gps.HealthzResponse\x12F\n" +
	"\x0fGetPointsNearby\x12\x18.gps.PointsNearbyRequest\x1a\x19.gps.PointsNearbyResponse\x12/\n" +
	"\tGetPoints\x12\n" +
	".gps.Empty\x1a\x16.gps.GetPointsResponse\x12/\n" +
	"\tGetKiosks\x12\n" +
	".gps.Empty\x1a\x16.gps.GetKiosksResponse\x12C\n" +
	"\fGetKioskById\x12\x18.gps.GetKioskByIdRequest\x1a\x19.gps.GetKioskByIdResponse\x121\n" +
	"\x06Search\x12\x12.gps.SearchRequest\x1a\x13.gps.SearchResponse\x12C\n" +
	"\fTerminalPing\x12\x18.gps.TerminalPingRequest\x1a\x19.gps.TerminalPingResponse\x12.\n" +
	"\x05Login\x12\x11.gps.LoginRequest\x1a\x12.gps.LoginResponse\x127\n" +
	"\bRegister\x12\x14.gps.RegisterRequest\x1a\x15.gps.RegisterResponse\x124\n" +
	"\aRefresh\x12\x13.gps.RefreshRequest\x1a\x14.gps.RefreshResponse\x12@\n" +
	"\vCreatePoint\x12\x17.gps.CreatePointRequest\x1a\x18.gps.CreatePointResponse\x12@\n" +
	"\vUpdatePoint\x12\x17.gps.UpdatePointRequest\x1a\x18.gps.UpdatePointResponse\x12@\n" +
	"\vDeletePoint\x12\x17.gps.DeletePointRequest\x1a\x18.gps.DeletePointResponse\x12@\n" +
	"\vCreateKiosk\x12\x17.gps.CreateKioskRequest\x1a\x18.gps.CreateKioskResponse\x12@\n" +
	"\vUpdateKiosk\x12\x17.gps.UpdateKioskRequest\x1a\x18.gps.UpdateKioskResponse\x12@\n" +
	"\vDeleteKiosk\x12\x17.gps.DeleteKioskRequest\x1a\x18.gps.DeleteKioskResponseB\x16Z\x14gps_service/grpc/apib\x06proto3"

var (
	file_grpc_api_gps_proto_rawDescOnce sync.Once
	file_grpc_api_gps_proto_rawDescData []byte
)

func file_grpc_api_gps_proto_rawDescGZIP() []byte {
	file_grpc_api_gps_proto_rawDescOnce.Do(func() {
		file_grpc_api_gps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_api_gps_proto_rawDesc), len(file_grpc_api_gps_proto_rawDesc)))
	})
	return file_grpc_api_gps_proto_rawDescData
}

var file_grpc_api_gps_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_grpc_api_gps_proto_goTypes = []any{
	(*Empty)(nil),                // 0: gps.Empty
	(*HealthzResponse)(nil),      // 1: gps.HealthzResponse
	(*PointsNearbyRequest)(nil),  // 2: gps.PointsNearbyRequest
	(*PointsNearbyResponse)(nil), // 3: gps.PointsNearbyResponse
	(*NearbyPoint)(nil),          // 4: gps.NearbyPoint
	(*GetPointsResponse)(nil),    // 5: gps.GetPointsResponse
	(*Point)(nil),                // 6: gps.Point
	(*GetKiosksResponse)(nil),    // 7: gps.GetKiosksResponse
	(*GetKioskByIdRequest)(nil),  // 8: gps.GetKioskByIdRequest
	(*GetKioskByIdResponse)(nil), // 9: gps.GetKioskByIdResponse
	(*Kiosk)(nil),                // 10: gps.Kiosk
	(*SearchRequest)(nil),        // 11: gps.SearchRequest
	(*SearchResponse)(nil),       // 12: gps.SearchResponse
	(*SearchResult)(nil),         // 13: gps.SearchResult
	(*TerminalPingRequest)(nil),  // 14: gps.TerminalPingRequest
	(*TerminalPingResponse)(nil), // 15: gps.TerminalPingResponse
	(*LoginRequest)(nil),         // 16: gps.LoginRequest
	(*LoginResponse)(nil),        // 17: gps.LoginResponse
	(*RegisterRequest)(nil),      // 18: gps.RegisterRequest
	(*RegisterResponse)(nil),     // 19: gps.RegisterResponse
	(*RefreshRequest)(nil),       // 20: gps.RefreshRequest
	(*RefreshResponse)(nil),      // 21: gps.RefreshResponse
	(*CreatePointRequest)(nil),   // 22: gps.CreatePointRequest
	(*CreatePointResponse)(nil),  // 23: gps.CreatePointResponse
	(*UpdatePointRequest)(nil),   // 24: gps.UpdatePointRequest
	(*UpdatePointResponse)(nil),  // 25: gps.UpdatePointResponse
	(*DeletePointRequest)(nil),   // 26: gps.DeletePointRequest
	(*DeletePointResponse)(nil),  // 27: gps.DeletePointResponse
	(*CreateKioskRequest)(nil),   // 28: gps.CreateKioskRequest
	(*CreateKioskResponse)(nil),  // 29: gps.CreateKioskResponse
	(*UpdateKioskRequest)(nil),   // 30: gps.UpdateKioskRequest
	(*UpdateKioskResponse)(nil),  // 31: gps.UpdateKioskResponse
	(*DeleteKioskRequest)(nil),   // 32: gps.DeleteKioskRequest
	(*DeleteKioskResponse)(nil),  // 33: gps.DeleteKioskResponse
}
var file_grpc_api_gps_proto_depIdxs = []int32{
	4,  // 0: gps.PointsNearbyResponse.points:type_name -> gps.NearbyPoint
	6,  // 1: gps.GetPointsResponse.points:type_name -> gps.Point
	10, // 2: gps.GetKiosksResponse.kiosks:type_name -> gps.Kiosk
	10, // 3: gps.GetKioskByIdResponse.kiosk:type_name -> gps.Kiosk
	13, // 4: gps.SearchResponse.results:type_name -> gps.SearchResult
	6,  // 5: gps.CreatePointResponse.point:type_name -> gps.Point
	10, // 6: gps.CreateKioskResponse.kiosk:type_name -> gps.Kiosk
	0,  // 7: gps.GPSService.Healthz:input_type -> gps.Empty
	2,  // 8: gps.GPSService.GetPointsNearby:input_type -> gps.PointsNearbyRequest
	0,  // 9: gps.GPSService.GetPoints:input_type -> gps.Empty
	0,  // 10: gps.GPSService.GetKiosks:input_type -> gps.Empty
	8,  // 11: gps.GPSService.GetKioskById:input_type -> gps.GetKioskByIdRequest
	11, // 12: gps.GPSService.Search:input_type -> gps.SearchRequest
	14, // 13: gps.GPSService.TerminalPing:input_type -> gps.TerminalPingRequest
	16, // 14: gps.GPSService.Login:input_type -> gps.LoginRequest
	18, // 15: gps.GPSService.Register:input_type -> gps.RegisterRequest
	20, // 16: gps.GPSService.Refresh:input_type -> gps.RefreshRequest
	22, // 17: gps.GPSService.CreatePoint:input_type -> gps.CreatePointRequest
	24, // 18: gps.GPSService.UpdatePoint:input_type -> gps.UpdatePointRequest
	26, // 19: gps.GPSService.DeletePoint:input_type -> gps.DeletePointRequest
	28, // 20: gps.GPSService.CreateKiosk:input_type -> gps.CreateKioskRequest
	30, // 21: gps.GPSService.UpdateKiosk:input_type -> gps.UpdateKioskRequest
	32, // 22: gps.GPSService.DeleteKiosk:input_type -> gps.DeleteKioskRequest
	1,  // 23: gps.GPSService.Healthz:output_type -> gps.HealthzResponse
	3,  // 24: gps.GPSService.GetPointsNearby:output_type -> gps.PointsNearbyResponse
	5,  // 25: gps.GPSService.GetPoints:output_type -> gps.GetPointsResponse
	7,  // 26: gps.GPSService.GetKiosks:output_type -> gps.GetKiosksResponse
	9,  // 27: gps.GPSService.GetKioskById:output_type -> gps.GetKioskByIdResponse
	12, // 28: gps.GPSService.Search:output_type -> gps.SearchResponse
	15, // 29: gps.GPSService.TerminalPing:output_type -> gps.TerminalPingResponse
	17, // 30: gps.GPSService.Login:output_type -> gps.LoginResponse
	19, // 31: gps.GPSService.Register:output_type -> gps.RegisterResponse
	21, // 32: gps.GPSService.Refresh:output_type -> gps.RefreshResponse
	23, // 33: gps.GPSService.CreatePoint:output_type -> gps.CreatePointResponse
	25, // 34: gps.GPSService.UpdatePoint:output_type -> gps.UpdatePointResponse
	27, // 35: gps.GPSService.DeletePoint:output_type -> gps.DeletePointResponse
	29, // 36: gps.GPSService.CreateKiosk:output_type -> gps.CreateKioskResponse
	31, // 37: gps.GPSService.UpdateKiosk:output_type -> gps.UpdateKioskResponse
	33, // 38: gps.GPSService.DeleteKiosk:output_type -> gps.DeleteKioskResponse
	23, // [23:39] is the sub-list for method output_type
	7,  // [7:23] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_api_gps_proto_init() }
func file_grpc_api_gps_proto_init() {
	if File_grpc_api_gps_proto != nil {
		return
	}
	file_grpc_api_gps_proto_msgTypes[4].OneofWrappers = []any{}
	file_grpc_api_gps_proto_msgTypes[6].OneofWrappers = []any{}
	file_grpc_api_gps_proto_msgTypes[22].OneofWrappers = []any{}
	file_grpc_api_gps_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_api_gps_proto_rawDesc), len(file_grpc_api_gps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_api_gps_proto_goTypes,
		DependencyIndexes: file_grpc_api_gps_proto_depIdxs,
		MessageInfos:      file_grpc_api_gps_proto_msgTypes,
	}.Build()
	File_grpc_api_gps_proto = out.File
	file_grpc_api_gps_proto_goTypes = nil
	file_grpc_api_gps_proto_depIdxs = nil
}
