// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: grpc/api/gps.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPSService_Healthz_FullMethodName         = "/gps.GPSService/Healthz"
	GPSService_GetPointsNearby_FullMethodName = "/gps.GPSService/GetPointsNearby"
	GPSService_GetPoints_FullMethodName       = "/gps.GPSService/GetPoints"
	GPSService_GetKiosks_FullMethodName       = "/gps.GPSService/GetKiosks"
	GPSService_GetKioskById_FullMethodName    = "/gps.GPSService/GetKioskById"
	GPSService_Search_FullMethodName          = "/gps.GPSService/Search"
	GPSService_TerminalPing_FullMethodName    = "/gps.GPSService/TerminalPing"
	GPSService_Login_FullMethodName           = "/gps.GPSService/Login"
	GPSService_Register_FullMethodName        = "/gps.GPSService/Register"
	GPSService_Refresh_FullMethodName         = "/gps.GPSService/Refresh"
	GPSService_CreatePoint_FullMethodName     = "/gps.GPSService/CreatePoint"
	GPSService_UpdatePoint_FullMethodName     = "/gps.GPSService/UpdatePoint"
	GPSService_DeletePoint_FullMethodName     = "/gps.GPSService/DeletePoint"
	GPSService_CreateKiosk_FullMethodName     = "/gps.GPSService/CreateKiosk"
	GPSService_UpdateKiosk_FullMethodName     = "/gps.GPSService/UpdateKiosk"
	GPSService_DeleteKiosk_FullMethodName     = "/gps.GPSService/DeleteKiosk"
)

// GPSServiceClient is the client API for GPSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPSServiceClient interface {
	// Health check
	Healthz(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
	// Поиск точек рядом
	GetPointsNearby(ctx context.Context, in *PointsNearbyRequest, opts ...grpc.CallOption) (*PointsNearbyResponse, error)
	// Получить все точки
	GetPoints(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPointsResponse, error)
	// Получить все киоски
	GetKiosks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetKiosksResponse, error)
	// Получить киоск по ID
	GetKioskById(ctx context.Context, in *GetKioskByIdRequest, opts ...grpc.CallOption) (*GetKioskByIdResponse, error)
	// Поиск
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Пинг терминала
	TerminalPing(ctx context.Context, in *TerminalPingRequest, opts ...grpc.CallOption) (*TerminalPingResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// Точки (CRUD)
	CreatePoint(ctx context.Context, in *CreatePointRequest, opts ...grpc.CallOption) (*CreatePointResponse, error)
	UpdatePoint(ctx context.Context, in *UpdatePointRequest, opts ...grpc.CallOption) (*UpdatePointResponse, error)
	DeletePoint(ctx context.Context, in *DeletePointRequest, opts ...grpc.CallOption) (*DeletePointResponse, error)
	// Киоски (CRUD)
	CreateKiosk(ctx context.Context, in *CreateKioskRequest, opts ...grpc.CallOption) (*CreateKioskResponse, error)
	UpdateKiosk(ctx context.Context, in *UpdateKioskRequest, opts ...grpc.CallOption) (*UpdateKioskResponse, error)
	DeleteKiosk(ctx context.Context, in *DeleteKioskRequest, opts ...grpc.CallOption) (*DeleteKioskResponse, error)
}

type gPSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPSServiceClient(cc grpc.ClientConnInterface) GPSServiceClient {
	return &gPSServiceClient{cc}
}

func (c *gPSServiceClient) Healthz(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, GPSService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) GetPointsNearby(ctx context.Context, in *PointsNearbyRequest, opts ...grpc.CallOption) (*PointsNearbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointsNearbyResponse)
	err := c.cc.Invoke(ctx, GPSService_GetPointsNearby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) GetPoints(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPointsResponse)
	err := c.cc.Invoke(ctx, GPSService_GetPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) GetKiosks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetKiosksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKiosksResponse)
	err := c.cc.Invoke(ctx, GPSService_GetKiosks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) GetKioskById(ctx context.Context, in *GetKioskByIdRequest, opts ...grpc.CallOption) (*GetKioskByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKioskByIdResponse)
	err := c.cc.Invoke(ctx, GPSService_GetKioskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, GPSService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) TerminalPing(ctx context.Context, in *TerminalPingRequest, opts ...grpc.CallOption) (*TerminalPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminalPingResponse)
	err := c.cc.Invoke(ctx, GPSService_TerminalPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, GPSService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, GPSService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, GPSService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) CreatePoint(ctx context.Context, in *CreatePointRequest, opts ...grpc.CallOption) (*CreatePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePointResponse)
	err := c.cc.Invoke(ctx, GPSService_CreatePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) UpdatePoint(ctx context.Context, in *UpdatePointRequest, opts ...grpc.CallOption) (*UpdatePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePointResponse)
	err := c.cc.Invoke(ctx, GPSService_UpdatePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) DeletePoint(ctx context.Context, in *DeletePointRequest, opts ...grpc.CallOption) (*DeletePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePointResponse)
	err := c.cc.Invoke(ctx, GPSService_DeletePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) CreateKiosk(ctx context.Context, in *CreateKioskRequest, opts ...grpc.CallOption) (*CreateKioskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKioskResponse)
	err := c.cc.Invoke(ctx, GPSService_CreateKiosk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) UpdateKiosk(ctx context.Context, in *UpdateKioskRequest, opts ...grpc.CallOption) (*UpdateKioskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKioskResponse)
	err := c.cc.Invoke(ctx, GPSService_UpdateKiosk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPSServiceClient) DeleteKiosk(ctx context.Context, in *DeleteKioskRequest, opts ...grpc.CallOption) (*DeleteKioskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKioskResponse)
	err := c.cc.Invoke(ctx, GPSService_DeleteKiosk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPSServiceServer is the server API for GPSService service.
// All implementations must embed UnimplementedGPSServiceServer
// for forward compatibility.
type GPSServiceServer interface {
	// Health check
	Healthz(context.Context, *Empty) (*HealthzResponse, error)
	// Поиск точек рядом
	GetPointsNearby(context.Context, *PointsNearbyRequest) (*PointsNearbyResponse, error)
	// Получить все точки
	GetPoints(context.Context, *Empty) (*GetPointsResponse, error)
	// Получить все киоски
	GetKiosks(context.Context, *Empty) (*GetKiosksResponse, error)
	// Получить киоск по ID
	GetKioskById(context.Context, *GetKioskByIdRequest) (*GetKioskByIdResponse, error)
	// Поиск
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Пинг терминала
	TerminalPing(context.Context, *TerminalPingRequest) (*TerminalPingResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Точки (CRUD)
	CreatePoint(context.Context, *CreatePointRequest) (*CreatePointResponse, error)
	UpdatePoint(context.Context, *UpdatePointRequest) (*UpdatePointResponse, error)
	DeletePoint(context.Context, *DeletePointRequest) (*DeletePointResponse, error)
	// Киоски (CRUD)
	CreateKiosk(context.Context, *CreateKioskRequest) (*CreateKioskResponse, error)
	UpdateKiosk(context.Context, *UpdateKioskRequest) (*UpdateKioskResponse, error)
	DeleteKiosk(context.Context, *DeleteKioskRequest) (*DeleteKioskResponse, error)
	mustEmbedUnimplementedGPSServiceServer()
}

// UnimplementedGPSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPSServiceServer struct{}

func (UnimplementedGPSServiceServer) Healthz(context.Context, *Empty) (*HealthzResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedGPSServiceServer) GetPointsNearby(context.Context, *PointsNearbyRequest) (*PointsNearbyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPointsNearby not implemented")
}
func (UnimplementedGPSServiceServer) GetPoints(context.Context, *Empty) (*GetPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoints not implemented")
}
func (UnimplementedGPSServiceServer) GetKiosks(context.Context, *Empty) (*GetKiosksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKiosks not implemented")
}
func (UnimplementedGPSServiceServer) GetKioskById(context.Context, *GetKioskByIdRequest) (*GetKioskByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKioskById not implemented")
}
func (UnimplementedGPSServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGPSServiceServer) TerminalPing(context.Context, *TerminalPingRequest) (*TerminalPingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminalPing not implemented")
}
func (UnimplementedGPSServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGPSServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGPSServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedGPSServiceServer) CreatePoint(context.Context, *CreatePointRequest) (*CreatePointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePoint not implemented")
}
func (UnimplementedGPSServiceServer) UpdatePoint(context.Context, *UpdatePointRequest) (*UpdatePointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePoint not implemented")
}
func (UnimplementedGPSServiceServer) DeletePoint(context.Context, *DeletePointRequest) (*DeletePointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePoint not implemented")
}
func (UnimplementedGPSServiceServer) CreateKiosk(context.Context, *CreateKioskRequest) (*CreateKioskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKiosk not implemented")
}
func (UnimplementedGPSServiceServer) UpdateKiosk(context.Context, *UpdateKioskRequest) (*UpdateKioskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKiosk not implemented")
}
func (UnimplementedGPSServiceServer) DeleteKiosk(context.Context, *DeleteKioskRequest) (*DeleteKioskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKiosk not implemented")
}
func (UnimplementedGPSServiceServer) mustEmbedUnimplementedGPSServiceServer() {}
func (UnimplementedGPSServiceServer) testEmbeddedByValue()                    {}

// UnsafeGPSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPSServiceServer will
// result in compilation errors.
type UnsafeGPSServiceServer interface {
	mustEmbedUnimplementedGPSServiceServer()
}

func RegisterGPSServiceServer(s grpc.ServiceRegistrar, srv GPSServiceServer) {
	// If the following call panics, it indicates UnimplementedGPSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPSService_ServiceDesc, srv)
}

func _GPSService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).Healthz(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_GetPointsNearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointsNearbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).GetPointsNearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_GetPointsNearby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).GetPointsNearby(ctx, req.(*PointsNearbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_GetPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).GetPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_GetPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).GetPoints(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_GetKiosks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).GetKiosks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_GetKiosks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).GetKiosks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_GetKioskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKioskByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).GetKioskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_GetKioskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).GetKioskById(ctx, req.(*GetKioskByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_TerminalPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).TerminalPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_TerminalPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).TerminalPing(ctx, req.(*TerminalPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_CreatePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).CreatePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_CreatePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).CreatePoint(ctx, req.(*CreatePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_UpdatePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).UpdatePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_UpdatePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).UpdatePoint(ctx, req.(*UpdatePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_DeletePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).DeletePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_DeletePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).DeletePoint(ctx, req.(*DeletePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_CreateKiosk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKioskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).CreateKiosk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_CreateKiosk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).CreateKiosk(ctx, req.(*CreateKioskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_UpdateKiosk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKioskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).UpdateKiosk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_UpdateKiosk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).UpdateKiosk(ctx, req.(*UpdateKioskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPSService_DeleteKiosk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKioskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSServiceServer).DeleteKiosk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPSService_DeleteKiosk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSServiceServer).DeleteKiosk(ctx, req.(*DeleteKioskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPSService_ServiceDesc is the grpc.ServiceDesc for GPSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gps.GPSService",
	HandlerType: (*GPSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _GPSService_Healthz_Handler,
		},
		{
			MethodName: "GetPointsNearby",
			Handler:    _GPSService_GetPointsNearby_Handler,
		},
		{
			MethodName: "GetPoints",
			Handler:    _GPSService_GetPoints_Handler,
		},
		{
			MethodName: "GetKiosks",
			Handler:    _GPSService_GetKiosks_Handler,
		},
		{
			MethodName: "GetKioskById",
			Handler:    _GPSService_GetKioskById_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _GPSService_Search_Handler,
		},
		{
			MethodName: "TerminalPing",
			Handler:    _GPSService_TerminalPing_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GPSService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GPSService_Register_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _GPSService_Refresh_Handler,
		},
		{
			MethodName: "CreatePoint",
			Handler:    _GPSService_CreatePoint_Handler,
		},
		{
			MethodName: "UpdatePoint",
			Handler:    _GPSService_UpdatePoint_Handler,
		},
		{
			MethodName: "DeletePoint",
			Handler:    _GPSService_DeletePoint_Handler,
		},
		{
			MethodName: "CreateKiosk",
			Handler:    _GPSService_CreateKiosk_Handler,
		},
		{
			MethodName: "UpdateKiosk",
			Handler:    _GPSService_UpdateKiosk_Handler,
		},
		{
			MethodName: "DeleteKiosk",
			Handler:    _GPSService_DeleteKiosk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/api/gps.proto",
}
